webtalk_init -webtalk_dir C:/Users/grego/Documents/TortoiseGIT/ECE6276_project/ECE-6276/firmware/project_1/project_1.sim/sim_1/behav/xsim.dir/TB_FILTER_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Nov 11 15:25:52 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1957588" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a59b7ef2-16b9-4f19-b6c2-ab458734e2c4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fe3269faccf242ec98c8c04a75a3c517" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2395 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "60 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "10.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15684_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1889308458 -regid "" -xml C:/Users/grego/Documents/TortoiseGIT/ECE6276_project/ECE-6276/firmware/project_1/project_1.sim/sim_1/behav/xsim.dir/TB_FILTER_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/grego/Documents/TortoiseGIT/ECE6276_project/ECE-6276/firmware/project_1/project_1.sim/sim_1/behav/xsim.dir/TB_FILTER_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/grego/Documents/TortoiseGIT/ECE6276_project/ECE-6276/firmware/project_1/project_1.sim/sim_1/behav/xsim.dir/TB_FILTER_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
