#
# Vivado (TM) v2017.2 (64-bit)
#
# project.tcl: Tcl script for re-creating project 'project_1'
#
# Generated by Vivado on Sun Nov 19 12:34:05 -0500 2017
# IP Build 1909766 on Thu Jun 15 19:58:00 MDT 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/sobel.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/packages/generic_utilities.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/fake_camera.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/project_top.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/tb_sobel.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/filter_mask_3x3.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/tb_filter_mask_3x3.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/tb_sobel_image.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/sobel_wrapper.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/project_1/project_1.srcs/sources_1/ip/line_buff_4/line_buff_4.xci"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/project_1/project_1.srcs/sources_1/ip/line_buff_159/line_buff_159.xci"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/project_1/project_1.srcs/sources_1/ip/line_buff_175/line_buff_175.xci"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/constraints/Basys3_Master.xdc"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/tb_project_top.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/firmware/vhdl_src/sobel.vhd"
#    "C:/Users/Bryce/Desktop/github/ECE-6276/matlab/output_files/image_data.txt"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/project_1"]"

# Create project
create_project project_1 ./project_1 -part xc7a100tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects project_1]
set_property -name "board_part" -value "digilentinc.com:nexys4_ddr:part0:1.1" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/project_1.cache/ip" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "xpm_libraries" -value "XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/vhdl_src/sobel.vhd"]"\
 "[file normalize "$origin_dir/packages/generic_utilities.vhd"]"\
 "[file normalize "$origin_dir/vhdl_src/fake_camera.vhd"]"\
 "[file normalize "$origin_dir/vhdl_src/project_top.vhd"]"\
 "[file normalize "$origin_dir/vhdl_src/tb_sobel.vhd"]"\
 "[file normalize "$origin_dir/vhdl_src/filter_mask_3x3.vhd"]"\
 "[file normalize "$origin_dir/vhdl_src/tb_filter_mask_3x3.vhd"]"\
 "[file normalize "$origin_dir/vhdl_src/tb_sobel_image.vhd"]"\
 "[file normalize "$origin_dir/vhdl_src/sobel_wrapper.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/vhdl_src/sobel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/packages/generic_utilities.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/vhdl_src/fake_camera.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/vhdl_src/project_top.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "work" -objects $file_obj

set file "$origin_dir/vhdl_src/tb_sobel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/vhdl_src/filter_mask_3x3.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/vhdl_src/tb_filter_mask_3x3.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/vhdl_src/tb_sobel_image.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/vhdl_src/sobel_wrapper.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "SOBEL_WRAPPER" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/project_1/project_1.srcs/sources_1/ip/line_buff_4/line_buff_4.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/project_1/project_1.srcs/sources_1/ip/line_buff_159/line_buff_159.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/project_1/project_1.srcs/sources_1/ip/line_buff_175/line_buff_175.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constraints/Basys3_Master.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/constraints/Basys3_Master.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/vhdl_src/tb_project_top.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/vhdl_src/tb_project_top.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "TB_FILTER" -objects $obj

# Create 'sim_sobel' fileset (if not found)
if {[string equal [get_filesets -quiet sim_sobel] ""]} {
  create_fileset -simset sim_sobel
}

# Set 'sim_sobel' fileset object
set obj [get_filesets sim_sobel]
set files [list \
 "[file normalize "$origin_dir/vhdl_src/sobel.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_sobel' fileset file properties for remote files
set file "$origin_dir/vhdl_src/sobel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_sobel] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sim_sobel' fileset file properties for local files
# None

# Set 'sim_sobel' fileset properties
set obj [get_filesets sim_sobel]
set_property -name "top" -value "tb_sobel" -objects $obj
set_property -name "xsim.simulate.runtime" -value "10000 ns" -objects $obj

# Create 'sim_filter_mask_3x3' fileset (if not found)
if {[string equal [get_filesets -quiet sim_filter_mask_3x3] ""]} {
  create_fileset -simset sim_filter_mask_3x3
}

# Set 'sim_filter_mask_3x3' fileset object
set obj [get_filesets sim_filter_mask_3x3]
# Empty (no sources present)

# Set 'sim_filter_mask_3x3' fileset properties
set obj [get_filesets sim_filter_mask_3x3]
set_property -name "top" -value "tb_filter_mask_3x3" -objects $obj
set_property -name "xsim.simulate.runtime" -value "500 ns" -objects $obj

# Create 'tb_sobel_image' fileset (if not found)
if {[string equal [get_filesets -quiet tb_sobel_image] ""]} {
  create_fileset -simset tb_sobel_image
}

# Set 'tb_sobel_image' fileset object
set obj [get_filesets tb_sobel_image]
set files [list \
 "[file normalize "$origin_dir/../matlab/output_files/image_data.txt"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'tb_sobel_image' fileset file properties for remote files
# None

# Set 'tb_sobel_image' fileset file properties for local files
# None

# Set 'tb_sobel_image' fileset properties
set obj [get_filesets tb_sobel_image]
set_property -name "top" -value "tb_sobel_image" -objects $obj
set_property -name "xsim.simulate.runtime" -value "400000 ns" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:project_1"
